- hosts: localhost
  pre_tasks:
  - name: Update pacman
    become: true
    pacman:
      update_cache: true
      upgrade: yes
  tasks:
    - name: install base 
      pacman:
        update_cache: yes
        name:
          - curl
          - base-devel
          - cmake
          - stow
          - zsh
          - starship
          - fzf
          - tmux
          - python-pip
          - python-pexpect
          - python-setuptools
    - name: add the user to the root group
      user:
        name: "{{ ansible_user }}"
        groups: root
        append: yes
    #- name: run install
      #become: true
      #shell: sudo ansible-playbook local.yml
