- hosts: localhost
  pre_tasks:
  - name: Update pacman
    become: true
    pacman:
      update_cache: true
      upgrade: yes
  tasks:
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/yay.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/tmux.yml
    - include_tasks: tasks/nvim.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/apps.yml
    - include_tasks: tasks/java.yml
