    - name: install apps 
      become: true
      pacman:
        name:
          - mpv
          - vifm
          - nemo
          - obs-studio
          - v4l2loopback-dkms
          - discord
          - docker
          - kitty
          - fzf
          - easyeffects
          - playerctl
          - rofi
          - qutebrowser
          - zoxide
      tags:
      - apps
      - install

    - name: install more apps with yay
      become: true
      shell: runuser -l {{ ansible_user }} -c 'yay -Syu spotify brave-bin google-chrome slack-desktop gummy lazygit --noconfirm' 
      tags:
      - apps   
      - install  

    - name: clean cache
      become: true
      shell: pacman -Sc 
      tags:
      - apps  
      - install    
