    - name: install apps 
      pacman:
        update_cache: yes
        name:
          - spotify-launcher 
          - vlc
          - vifm
          - nvidia
          - xclip
          - obs-studio
          - discord
          - docker
          - scrot
          - kitty

    - name: clean cache
      shell: pacman -Sc 

    - name: install brave
      shell: runuser -l {{ ansible_user }} -c 'yay -S brave-bin --noconfirm' 

    - name: install google-chrome 
      shell: runuser -l {{ ansible_user }} -c 'yay -S google-chrome --noconfirm' 

    - name: install slack 
      shell: runuser -l {{ ansible_user }} -c 'yay -S slack-desktop --noconfirm' 

    - name: install gummy 
      shell: runuser -l {{ ansible_user }} -c 'yay -S gummy --noconfirm' 

    - name: Create Gradle installation directory
      file:
        path: "{{ gradle_installation_path }}"
        state: directory

    - name: Download Gradle
      get_url:
        url: "{{ gradle_download_url }}"
        dest: "/tmp/{{ gradle_zip_file }}"

    - name: Unzip Gradle
      ansible.builtin.unarchive:
        src: "/tmp/{{ gradle_zip_file }}"
        dest: "{{ gradle_installation_path }}"
        remote_src: yes

    - name: Verify Gradle installation
      ansible.builtin.command: "{{ gradle_installation_path }}/gradle-{{ gradle_version }}/bin/gradle -v"
