    - name: install base packages
      become: true
      pacman:
        name:
          - curl
          - base-devel
          - cmake
          - python-pip
          - python-pexpect
          - python-setuptools
          - unzip
          - ripgrep
          - xorg-server
          - nvidia
          - pavucontrol
      tags:
      - core      
      - install

# USERS PERMISSIONS  ---------------------------------------------------------
    - name: add the user to the root group
      become: true
      user:
        name: "{{ ansible_user }}"
        groups: root
        append: yes
      tags:
      - core 
      - install

    - name: disable need for sudo password for the current user
      become: true
      lineinfile:
        path: "/etc/sudoers.d/02_no_pswd_for_{{ ansible_env.SUDO_UID }}"
        state: present
        line: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s
        create: yes
      tags:
      - core 
      - install


# SYSTEM SETTINGS CHANGES ----------------------------------------------------

    - name: pacman - enable color
      become: true
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#Color$'
        line: 'Color'
      tags:
      - core 
      - install

    - name: pacman - enable ParallelDownloads = 5
      become: true
      lineinfile:
        path: /etc/pacman.conf
        regexp: '#ParallelDownloads = 5'
        line: 'ParallelDownloads = 5'
      tags:
      - core 
      - install

