    - name: install stow 
      pacman:
        name:
          - stow
      tags:
      - dotfiles 
      - install

    - name: clone dotfiles
      git:
        repo: 'https://github.com/tonocarvacho/.dotfiles'
        dest: "/home/{{ ansible_user }}/.dotfiles"
      tags:
      - dotfiles 
      - install

    - name: stow dotfiles
      shell: cd /home/{{ ansible_user }}/.dotfiles && stow zsh && stow fzf && stow starship && stow config && stow tmux && stow bin -t /usr/local/bin && stow vifm && stow hypr
      tags:
      - dotfiles 
      - install
