    - name: install stow 
      become: true
      pacman:
        name:
          - stow
      tags:
      - dotfiles 
      - install

    - name: clone dotfiles
      become: true
      become_user: "{{ ansible_user }}"
      git:
        repo: 'git@github.com:tonocarvacho/.dotfiles.git'
        dest: "/home/{{ ansible_user }}/.dotfiles"
      tags:
      - dotfiles 
      - install

    - name: stow dotfiles
      become: true
      become_user: "{{ ansible_user }}"
      shell: cd /home/{{ ansible_user }}/.dotfiles && stow -SR zsh fzf starship nvim tmux bin vifm hypr waybar kitty images fonts
      tags:
      - dotfiles 
      - install

    # - name: copy tmux-sessionizer
    #   become: true
    #   become_user: "{{ ansible_user }}"
    #   copy:
    #     src: /home/{{ ansible_user }}/.dotfiles/bin/.local/bin/tmux-sessionizer
    #     dest: /usr/local/bin/tmux-sessionizer
    #   tags:
    #   - dotfiles 
    #   - install