    - name: install stow 
      become: true
      pacman:
        name:
          - stow
      tags:
      - dotfiles 
      - install

    - name: clone dotfiles
      become: true
      become_user: "{{ ansible_user }}"
      git:
        repo: 'https://github.com/tonocarvacho/.dotfiles'
        dest: "/home/{{ ansible_user }}/.dotfiles"
      tags:
      - dotfiles 
      - install

    - name: stow dotfiles
      become: true
      become_user: "{{ ansible_user }}"
      shell: cd /home/{{ ansible_user }}/.dotfiles && stow zsh && stow fzf && stow starship && stow config && stow tmux && stow bin && stow vifm && stow hypr && stow waybar && stow kitty && stow images
      tags:
      - dotfiles 
      - install

    - name: copy tmux-sessionizer
      become: true
      copy:
        src: /home/{{ ansible_user }}/.dotfiles/bin/.local/bin/tmux-sessionizer
        dest: /usr/local/bin/tmux-sessionizer
      tags:
      - dotfiles 
      - install