    - name: Remove neovim
      shell: rm -rf /home/{{ ansible_user }}/neovim
      tags:
      - install
      - nvim

    - name: Get Packer
      git:
        repo: 'https://github.com/wbthomason/packer.nvim'
        dest: "/home/{{ ansible_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
      tags:
      - install
      - nvim

    - name: Clone Neovim
      git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: "/home/{{ ansible_user }}/neovim"
      tags:
      - install
      - nvim

    - name: Build neovim
      shell: "cd /home/{{ ansible_user }}/neovim && make -j 20"
      tags:
      - install
      - nvim

    - name: Install neovim
      shell: "cd /home/{{ ansible_user }}/neovim && make install"
      tags:
      - install
      - nvim

    - name: Neovim Plugin Development 1
      become: true
      pacman:
        update_cache: yes
        name:
          - luarocks 
      tags:
      - install
      - nvim

    - name: Neovim Plugin Development 2 luacheck
      become: true
      shell: luarocks install luacheck
      tags:
      - install
      - nvim
