    - name: install tmux 
      become: true
      pacman:
        update_cache: yes
        name:
          - tmux
      tags:
      - install
      - tmux

    - name: install gitmux
      become: true
      shell: runuser -l {{ ansible_user }} -c 'yay -S gitmux --noconfirm' 
      tags:
      - install
      - tmux
