    - name: install zsh 
      become: yes
      pacman:
        update_cache: yes
        name:
          - zsh
          - starship
      tags:
      - install
      - zsh

    - name: Install zsh-autosuggestions
      git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions'
        dest: "/home/{{ ansible_user }}/.zsh/zsh-autosuggestions"
      tags:
      - install
      - zsh

    - name: Install zsh-syntax-highlighting 
      git:
        repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
        dest: "/home/{{ ansible_user }}/.zsh/zsh-syntax-highlighting"
      tags:
      - install
      - zsh

    - name: set zsh default
      shell: chsh -s $(which zsh)
      tags:
      - install
      - zsh

